apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector7
spec:
  podSelector:
    matchLabels:
      app: drone7
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gcs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector2
spec:
  podSelector:
    matchLabels:
      app: drone2
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gcs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector8
spec:
  podSelector:
    matchLabels:
      app: drone8
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gcs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector13
spec:
  podSelector:
    matchLabels:
      app: drone13
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gcs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector9
spec:
  podSelector:
    matchLabels:
      app: drone9
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone16]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector16
spec:
  podSelector:
    matchLabels:
      app: drone16
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone9]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector14
spec:
  podSelector:
    matchLabels:
      app: drone14
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone19]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector4
spec:
  podSelector:
    matchLabels:
      app: drone4
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone10, drone19]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector19
spec:
  podSelector:
    matchLabels:
      app: drone19
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone14, drone4, drone17]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector17
spec:
  podSelector:
    matchLabels:
      app: drone17
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone19]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector15
spec:
  podSelector:
    matchLabels:
      app: drone15
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gcs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector10
spec:
  podSelector:
    matchLabels:
      app: drone10
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone4, drone3]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector5
spec:
  podSelector:
    matchLabels:
      app: drone5
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gcs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector3
spec:
  podSelector:
    matchLabels:
      app: drone3
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone10, drone20]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector20
spec:
  podSelector:
    matchLabels:
      app: drone20
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone3, drone1]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector1
spec:
  podSelector:
    matchLabels:
      app: drone1
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone11, drone20]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector11
spec:
  podSelector:
    matchLabels:
      app: drone11
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone1, drone6]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector18
spec:
  podSelector:
    matchLabels:
      app: drone18
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gcs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector12
spec:
  podSelector:
    matchLabels:
      app: drone12
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone6]}
        - {key: tier, operator: In, values: [drone]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-selector6
spec:
  podSelector:
    matchLabels:
      app: drone6
      tier: drone
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [gcs, drone11, drone12]}
        - {key: tier, operator: In, values: [drone]}
---
