apiVersion: v1
kind: Pod
metadata:
  name: drone1
  namespace: default
  labels:
    app: drone1
    tier: drone
spec:
  hostname: drone1
  dnsPolicy: ClusterFirst
  containers: 
    - name: drone1
      image: cyu72/drone:latest
      env:
        - name: PARAM1
          value: "drone1"
        - name: PARAM2
          value: "65456"
        - name: PARAM3
          value: "1"
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Service
metadata:
  name: drone1-service
spec:
  selector:
    app: drone1
    tier: drone
  ports:
  - protocol: UDP
    port: 80
    targetPort: 65456
---
apiVersion: v1
kind: Pod
metadata:
  name: drone2
  namespace: default
  labels:
    app: drone2
    tier: drone
spec:
  hostname: drone2
  dnsPolicy: ClusterFirst
  containers: 
    - name: drone2
      image: cyu72/drone:latest
      env:
        - name: PARAM1
          value: "drone2"
        - name: PARAM2
          value: "65456"
        - name: PARAM3
          value: "2"
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Service
metadata:
  name: drone2-service
spec:
  selector:
    app: drone2
    tier: drone
  ports:
  - protocol: UDP
    port: 80
    targetPort: 65456
---
apiVersion: v1
kind: Pod
metadata:
  name: drone3
  namespace: default
  labels:
    app: drone3
    tier: drone
spec:
  hostname: drone3
  dnsPolicy: ClusterFirst
  containers: 
    - name: drone3
      image: cyu72/drone:latest
      env:
        - name: PARAM1
          value: "drone3"
        - name: PARAM2
          value: "65456"
        - name: PARAM3
          value: "3"
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Service
metadata:
  name: drone3-service
spec:
  selector:
    app: drone3
    tier: drone
  ports:
  - protocol: UDP
    port: 80
    targetPort: 65456
---
apiVersion: v1
kind: Pod
metadata:
  name: gcs
  namespace: default
  labels:
    app: gcs
    tier: drone
spec:
  hostname: gcs
  dnsPolicy: ClusterFirst
  containers: 
    - name: gcs
      image: cyu72/gcs:latest
      stdin: true
      tty: true
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Service
metadata:
  name: drone-broadcast-service
  namespace: default
spec:
  selector:
    tier: drone
  ports:
    - protocol: UDP
      port: 80
      targetPort: 65456