apiVersion: v1
kind: Pod
metadata:
  name: drone1
  labels:
    app: drone
spec:
  containers: 
    - name: drone1
      image: cyu72/drone:latest
      env:
        - name: PARAM1
          value: "drone1"
        - name: PARAM2
          value: "65456"
        - name: PARAM3
          value: "1"
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Pod
metadata:
  name: drone2
  labels:
    app: drone
spec:
  containers: 
    - name: drone2
      image: cyu72/drone:latest
      env:
        - name: PARAM1
          value: "drone2"
        - name: PARAM2
          value: "65456"
        - name: PARAM3
          value: "2"
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Pod
metadata:
  name: drone3
  labels:
    app: drone
spec:
  containers: 
    - name: drone3
      image: cyu72/drone:latest
      env:
        - name: PARAM1
          value: "drone3"
        - name: PARAM2
          value: "65456"
        - name: PARAM3
          value: "3"
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Pod
metadata:
  name: gcs
  labels:
    app: drone
spec:
  containers: 
    - name: gcs
      image: cyu72/gcs:latest
      stdin: true
      tty: true
      ports:
        - protocol: UDP
          containerPort: 65456
---
apiVersion: v1
kind: Service
metadata:
  name: drone-broadcast-service
spec:
  selector:
    app: drone
  ports:
    - protocol: UDP
      port: 65456
      targetPort: 65456