version: '3'
services:
    drone1:
        build:
            context: ./src
            dockerfile: Dockerfile.drone
        image: drone:latest
        environment:
            PARAM1: drone1
            PARAM2: 65456
            PARAM3: 1
        networks:
            - AODV
    
    drone2:
        build:
            context: ./src
            dockerfile: Dockerfile.drone
        image: drone:latest
        environment:
            PARAM1: drone2
            PARAM2: 65456
            PARAM3: 2
        networks:
            - AODV
    
    drone3:
        build:
            context: ./src
            dockerfile: Dockerfile.drone
        image: drone:latest
        environment:
            PARAM1: drone3
            PARAM2: 65456
            PARAM3: 3
        networks:
            - AODV
    
    groundControlService:
        build:
            context: ./src
            dockerfile: Dockerfile.gcs
        image: gcs:latest
        stdin_open: true  
        tty: true  
        networks:
            - AODV

networks:
    AODV:
        name: AODV
        external: true