version: '3'
services:
  drone:
    image: cyu72/drone:latest
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
    env_file:
      - config.env
